### ISSUE TITLE
Codemirror code block colors

### ISSUE THREAD

**Issue by kirso** [dmytrodubinin/Harmony-theme-for-Logseq#6]
Trying to figure out whether this is the correct color scheme that was intended? 

![image](https://user-images.githubusercontent.com/2138870/230808734-ba1e85cd-8325-414f-8097-e2b5793eca1d.png)

Screenshots are showing something different but its a python example.

Tried both methods (marketplace + customCSS) but it seems like I am getting the default logseq colors.

**Comment by dmytrodubinin** [comment]
I see that your code type is javascript and not python. You need to change code type, here is the demo:

![Screencast from 2023-04-10 11-40-51](https://user-images.githubusercontent.com/8066458/230868050-4a836ebd-e77d-4ffb-9be3-4fba8528ee25.gif)

For now, the theme is using the standard colors of the Logseq code so that there is a minimum of contention for any further changes. Initially, the colors were modified, but the developers finalized this part of the design and I left their version.

Most likely the above problem is in the incorrect type of code.
